# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/alek_et_al"

[social.params]
icon = "instagram"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/alekzhang"

[social.params]
icon = "x"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/alekzhang"

[social.params]
icon = "github"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:alekzhang@gmail.com"

[social.params]
icon = "gmail"

